version: 2.1
jobs:
  do-setup:
    docker:
      - image: circleci/ruby:2.4-node
    steps:
      - checkout
  run-test-1:
    docker:
      - image: circleci/ruby:2.4-node
    steps:
        - checkout
  run-test-2:
    docker:
      - image: circleci/ruby:2.4-node
    steps:
      - checkout
  prepare-result:
    docker:
      - image: circleci/ruby:2.4-node
    steps:
      - checkout

workflows:
  my-workflow:
    jobs:
      - do-setup
      - run-test-1:
          requires:
            - do-setup
      - run-test-2:
          requires:
            - do-setup
      - prepare-result:
          requires:
            - run-test-1
            - run-test-2