version: 2.1

orbs:
  browser-tools: circleci/browser-tools@1.4.6
  python: circleci/python@2.0.3

commands:
  install-dependencies:
    steps:
      - python/install-packages:
          pip-dependency-file: requirement.txt
          pkg-manager: pip
  setup-browser:
    steps:
      - browser-tools/install-browser-tools
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - run:
          name: Verify Browser installation
          command: |
            google-chrome --version
            firefox --version
            geckodriver --version
            chromedriver --version
  run-tests:
    steps:
      - run:
          name: "Run Test Cases"
          command: |
              robot -d Results -v env:prod -i Smoke TestSuite/SmokeTestCommerceDashboard/
  prepare-result:
      steps:
        - store_artifacts:
            path: Results
            destination: artifact-file

jobs:
  run-test:
    docker:
      - image: cimg/python:3.10.5-browsers
    steps:
      - checkout
      - install-dependencies
      - setup-browser
      - run-tests
      - prepare-result

workflows:
  prepare-and-run-test:
    jobs:
      - run-test