version: 2.1
jobs:
  do-setup:
    parameters:
      sheet-name:
        description: this is a test data sheet name
        type: string
    docker:
      - image: circleci/ruby:<< parameters.sheet-name >>
    steps:
      - checkout

workflows:
  my-workflow:
    jobs:
      - do-setup:
          matrix:
            parameters:
              sheet-name: [latest, 2.4-node]