version: 2.1
jobs:
  job:
    docker:
      - image: circleci/ruby:2.4-node
    steps:
      - checkout
  job1:
    docker:
      - image: circleci/ruby:2.4-node
    steps:
        - checkout
  job2:
    docker:
      - image: circleci/ruby:2.4-node
    steps:
      - checkout

workflows:
  my-workflow:
    jobs:
      - job
      - job1:
          requires:
            - job
      - job2:
          requires:
            - job