version: 2.1
jobs:
  job1:
    docker:
      - image: cimg/base:2022
    steps:
      - checkout
  job2:
    docker:
      - image: cimg/base:2022
    steps:
        - checkout

workflows:
  my-workflow:
    jobs:
      - job1
      - job2