version: 2.1
setup: true
orbs:
  browser-tools: circleci/browser-tools@1.3.0
  python: circleci/python@2.0.3

commands:
  install-dependencies:
    steps:
      - python/install-packages:
          pip-dependency-file: requirement.txt
          pkg-manager: pip
  setup-browser:
    steps:
      - browser-tools/install-browser-tools:
          chrome-version: 103.0.5060.53
      - run:
          name: Verify Browser installation
          command: |
            google-chrome --version
            firefox --version
            geckodriver --version
            chromedriver --version
  run-tests:
    parameters:
      to:
        type: string
    steps:
      - run:
          name: "Run Test Cases"
          command: |
              robot -d Results --output original.xml -v env:prod -i <<parameters.to>> TGM/
  prepare-result:
      steps:
        - store_artifacts:
            path: Results
            destination: artifact-file

jobs:
  run-test:
    circleci_ip_ranges: true
    docker:
      - image: cimg/python:3.10.5-browsers
    steps:
      - checkout
      - install-dependencies
      - setup-browser
      - run-tests
      - prepare-result

workflows:
  prepare-and-run-test:
    jobs:
      - run-test