version: 2.1

orbs:
  browser-tools: circleci/browser-tools@1.3.0
  python: circleci/python@2.0.3

commands:
  install-dependencies:
    steps:
      - python/install-packages:
          pip-dependency-file: requirement.txt
          pkg-manager: pip
  setup-browser:
    steps:
      - browser-tools/install-browser-tools:
          chrome-version: 103.0.5060.53
      - run:
          name: Verify Browser installation
          command: |
            google-chrome --version
            firefox --version
            geckodriver --version
            chromedriver --version
  run-tests:
    steps:
      - run:
          name: "Run Test Cases"
          command: |
              robot -d Results --output original.xml -v env:prod -i apply_theme TGM/
  run-fail-tests:
    steps:
      - run:
          name: "Re-Run Fail Test Cases"
          command: |
            robot -d Results --prerunmodifier DataDriver.rerunfailed:Results/original.xml --output rerun.xml -v env:prod -i apply_theme TGM/
  merge-result:
    steps:
      - run:
          name: "Prepare final result"
          command: |
            rebot -d Results --merge Results/original.xml Results/rerun.xml
  prepare-result:
      steps:
        - store_artifacts:
            path: Results
            destination: artifact-file

jobs:
  run-test:
    circleci_ip_ranges: true
    docker:
      - image: cimg/python:3.10.5-browsers
    steps:
      - checkout
      - install-dependencies
      - setup-browser
      - run-tests
      - run-fail-tests
      - merge-result
      - prepare-result

workflows:
  prepare-and-run-test:
    jobs:
      - run-test