url = "https://www.instamojo.com/accounts/login"
browser = "chrome"
username = "amit_kt501"
password = "12345678"
storeurl = "https://amit-kt501.myinstamojo.com/"
storeemail = "abinaya.g@instamojo.com"
storepassword = "12345678"
